server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: SCHEDULER_DEV

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/scheduler_dev?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  jwt:
    secret: SecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey

    token:
      expired:
        second: 60
        minute: 60
        hour: 12